### PR TITLE
add support for RHEL9

### PR DESCRIPTION
**Pull request by vchepkov**
Any hope to get a new release?

### CODE REVIEW

**Comment by ekohl** [comment]
I noticed there is no CI, so I first want to get https://github.com/redhataccess/puppet-access_insights_client/pull/10 green and merged.

I don't have access to release. Perhaps @lphiri can help with that once merged.

**Comment by ekohl** [comment]
That was merged. Mind rebasing this?

**Comment by lphiri** [comment]
@vchepkov @ekohl  are you looking to release on puppet forge?

**Comment by vchepkov** [comment]
yes, please

**Comment by lphiri** [comment]
@ekohl  let me know when you are ready for a release and i will do one.

**Review by ekohl — APPROVED** [review]
I didn't verify this works on RHEL 9, but the module is fairly basic and if package names & configs didn't change I don't see why it wouldn't work. I've also seen sufficient contributions from @vchepkov to merge this.

Thanks @lphiri for offering to do the release. Given #10 was a breaking change, I'd say the next release should be a major version bump (so 2.0.0).

**Comment by vchepkov** [comment]
FYI, I use module on RHEL9, it works fine

**Pull request merged**
